In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("with_pca.csv")
df2=pd.read_csv("without_pca.csv")

In [3]:
df1

,radius_mean,texture_mean,smoothness_mean,symmetry_mean,fractal_dimension_mean,texture_se,smoothness_se,symmetry_se,PC1,PC2,class
0,20.57,17.77,0.08474,0.1812,0.05667,0.7339,0.005225,0.01389,0.135800,-0.036494,1
1,19.69,21.25,0.10960,0.2069,0.05999,0.7869,0.006150,0.02250,0.347207,0.067158,1
2,11.42,20.38,0.14250,0.2597,0.09744,1.1560,0.009110,0.05963,0.117664,0.409069,1
3,20.29,14.34,0.10030,0.1809,0.05883,0.7813,0.011490,0.01756,0.353084,-0.055668,1
4,12.45,15.70,0.12780,0.2087,0.07613,0.8902,0.007510,0.02165,-0.060263,0.131756,1
...,...,...,...,...,...,...,...,...,...,...,...
563,21.56,22.39,0.11100,0.1726,0.05623,1.2560,0.010300,0.01114,0.767615,-0.118759,1
564,20.13,28.25,0.09780,0.1752,0.05533,2.4630,0.005769,0.01898,0.358941,-0.053391,1
565,16.60,28.08,0.08455,0.1590,0.05648,1.0750,0.005903,0.01318,0.050868,-0.061141,1
566,20.60,29.33,0.11780,0.2397,0.07016,1.5950,0.006522,0.02324,0.340398,0.170290,1
567,7.76,24.54,0.05263,0.1587,0.05884,1.4280,0.007189,0.02676,-0.024631,-0.034019,0

In [4]:
df2

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst,class
0,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,1
1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,1
2,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,1
3,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,1
4,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,0.07613,...,23.75,103.40,741.6,0.17910,0.52490,0.5355,0.1741,0.3985,0.12440,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,1
564,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,1
565,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,1
566,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,1
567,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,0

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [6]:
x1=df1[[i for i in df1.columns if i !='class']]
y1=df1['class']
x2=df2[[i for i in df2.columns if i !='class']]
y2=df2['class']

In [7]:
x1_test, x1_train, y1_test, y1_train = train_test_split(x1, y1, test_size=0.2, random_state=42)
x2_test, x2_train, y2_test, y2_train = train_test_split(x1, y1, test_size=0.2, random_state=42)

In [8]:
knn_param={'n_neighbors':[3,5,7,9,11,13,15],'weights':['uniform','distance'],'algorithm':['auto','ball_tree','kd_tree','brute']}
lr_param={'penalty':['l1','l2','elasticnet'],'C':[0.01,0.1,1,10,100],'solver':['newton-cg','lbfgs','liblinear','sag','saga']}
svm_param={'C':[0.01,0.1,1,10,100],'kernel':['linear','poly','rbf','sigmoid'],'gamma':['scale','auto']}
dt_param={'criterion':['gini','entropy'],'max_depth':[None,5,10,15,20],'min_samples_split':[2,5,10],'min_samples_leaf':[1,2,4]}
gb_param={'n_estimators':[50,100,200],'learning_rate':[0.1,0.01,0.001],'max_depth':[3,5,7]}
rf_param={'n_estimators':[50,100,200],'max_depth':[None,5,10,15],'min_samples_split':[2,5,10],'min_samples_leaf':[1,2,4]}
xgb_param={'n_estimators':[50,100,200],'learning_rate':[0.1,0.01,0.001],'max_depth':[3,5,7]}
ad_param={'n_estimators':[50,100,200],'learning_rate':[0.1,0.01,0.001]}
grid_params={'knn':knn_param,'lr':lr_param,'svm':svm_param,'dt':dt_param,'gb':gb_param,'rf':rf_param,'xgb':xgb_param,'ad':ad_param}
models={'knn':KNeighborsClassifier(),'lr':LogisticRegression(),'svm':SVC(),'dt':DecisionTreeClassifier(),'gb':GradientBoostingClassifier(),'rf':RandomForestClassifier(),'xgb':XGBClassifier(),'ad':AdaBoostClassifier()}

In [9]:
import warnings
warnings.filterwarnings('ignore')

In [10]:
i=0
for name,params in grid_params.items():
    model=models[name]
    i+=1
    gr=RandomizedSearchCV(model,params,cv=5,n_iter=10,scoring='accuracy')
    gr.fit(x1_train,y1_train)
    gr_pred=gr.predict(x1_test)
    print(f"Model: {model}")
    print(f"Best Parameters: {gr.best_params_}")
    print(f"Accuracy: {accuracy_score(y1_test,gr_pred)}")    
    print(f"Precision: {precision_score(y1_test,gr_pred)}")
    print(f"Recall: {recall_score(y1_test,gr_pred)}")
    print(f"F1 Score: {f1_score(y1_test,gr_pred)}")
    print(f"ROC AUC Score: {roc_auc_score(y1_test,gr_pred)}")

Model: KNeighborsClassifier()
Best Parameters: {'weights': 'uniform', 'n_neighbors': 7, 'algorithm': 'auto'}
Accuracy: 0.8964757709251101
Precision: 0.9154929577464789
Recall: 0.7878787878787878
F1 Score: 0.8469055374592834
ROC AUC Score: 0.8731781482646535
Model: LogisticRegression()
Best Parameters: {'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}
Accuracy: 0.9074889867841409
Precision: 0.8819875776397516
Recall: 0.8606060606060606
F1 Score: 0.8711656441717791
ROC AUC Score: 0.8974310579846911
Model: SVC()
Best Parameters: {'kernel': 'linear', 'gamma': 'auto', 'C': 100}
Accuracy: 0.9361233480176211
Precision: 0.8953488372093024
Recall: 0.9333333333333333
F1 Score: 0.913946587537092
ROC AUC Score: 0.935524798154556
Model: DecisionTreeClassifier()
Best Parameters: {'min_samples_split': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'criterion': 'entropy'}
Accuracy: 0.8744493392070485
Precision: 0.7727272727272727
Recall: 0.9272727272727272
F1 Score: 0.8429752066115702
ROC AUC Score: 0.8857816923560868
Model: GradientBoostingClassifier()
Best Parameters: {'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.01}
Accuracy: 0.8744493392070485
Precision: 0.7903225806451613
Recall: 0.8909090909090909
F1 Score: 0.8376068376068376
ROC AUC Score: 0.8779804970116388
Model: RandomForestClassifier()
Best Parameters: {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': 10}
Accuracy: 0.9229074889867841
Precision: 0.8823529411764706
Recall: 0.9090909090909091
F1 Score: 0.8955223880597015
ROC AUC Score: 0.9199433784208871
Model: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)
Best Parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.1}
Accuracy: 0.9405286343612335
Precision: 0.9207317073170732
Recall: 0.9151515151515152
F1 Score: 0.9179331306990881
ROC AUC Score: 0.9350844080947887
Model: AdaBoostClassifier()
Best Parameters: {'n_estimators': 200, 'learning_rate': 0.1}
Accuracy: 0.9229074889867841
Precision: 0.877906976744186
Recall: 0.9151515151515152
F1 Score: 0.8961424332344213
ROC AUC Score: 0.9212435776449617

BEST MODEL WITH PCA : XGBOOST

In [11]:
i=0
for name,params in grid_params.items():
    model=models[name]
    i+=1
    gr=RandomizedSearchCV(model,params,cv=5,n_iter=10,scoring='accuracy')
    gr.fit(x2_train,y1_train)
    gr_pred=gr.predict(x2_test)
    print(f"Model: {model}")
    print(f"Best Parameters: {gr.best_params_}")
    print(f"Accuracy: {accuracy_score(y2_test,gr_pred)}")    
    print(f"Precision: {precision_score(y2_test,gr_pred)}")
    print(f"Recall: {recall_score(y2_test,gr_pred)}")
    print(f"F1 Score: {f1_score(y2_test,gr_pred)}")
    print(f"ROC AUC Score: {roc_auc_score(y2_test,gr_pred)}")

Model: KNeighborsClassifier()
Best Parameters: {'weights': 'uniform', 'n_neighbors': 11, 'algorithm': 'kd_tree'}
Accuracy: 0.9140969162995595
Precision: 0.95
Recall: 0.806060606060606
F1 Score: 0.8721311475409836
ROC AUC Score: 0.8909195763867044
Model: LogisticRegression()
Best Parameters: {'solver': 'newton-cg', 'penalty': 'l2', 'C': 100}
Accuracy: 0.9383259911894273
Precision: 0.9005847953216374
Recall: 0.9333333333333333
F1 Score: 0.9166666666666666
ROC AUC Score: 0.9372549019607843
Model: SVC()
Best Parameters: {'kernel': 'poly', 'gamma': 'auto', 'C': 1}
Accuracy: 0.9229074889867841
Precision: 0.8611111111111112
Recall: 0.9393939393939394
F1 Score: 0.8985507246376812
ROC AUC Score: 0.9264443745412604
Model: DecisionTreeClassifier()
Best Parameters: {'min_samples_split': 2, 'min_samples_leaf': 4, 'max_depth': 15, 'criterion': 'entropy'}
Accuracy: 0.9140969162995595
Precision: 0.9090909090909091
Recall: 0.8484848484848485
F1 Score: 0.877742946708464
ROC AUC Score: 0.9000209709552272
Model: GradientBoostingClassifier()
Best Parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.1}
Accuracy: 0.9074889867841409
Precision: 0.8554913294797688
Recall: 0.896969696969697
F1 Score: 0.8757396449704142
ROC AUC Score: 0.9052322533291393
Model: RandomForestClassifier()
Best Parameters: {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_depth': 15}
Accuracy: 0.9273127753303965
Precision: 0.8928571428571429
Recall: 0.9090909090909091
F1 Score: 0.9009009009009009
ROC AUC Score: 0.9234035860333438
Model: XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)
Best Parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.1}
Accuracy: 0.9405286343612335
Precision: 0.9207317073170732
Recall: 0.9151515151515152
F1 Score: 0.9179331306990881
ROC AUC Score: 0.9350844080947887
Model: AdaBoostClassifier()
Best Parameters: {'n_estimators': 200, 'learning_rate': 0.1}
Accuracy: 0.9229074889867841
Precision: 0.877906976744186
Recall: 0.9151515151515152
F1 Score: 0.8961424332344213
ROC AUC Score: 0.9212435776449617

BEST MODEL WITHOUT PCA : XGBOOST

THE ACCURACY,PRECISION AND RECALL OF BOTH DATASET BEFORE AND AFTER PCA ARE APPROXIMATELY SAME FOR BEST MODELS. BUT FOR OTHER MODELS THE PERFORMANCE METRICS HAVE IMPROVED LIKE 1-3 PERCENT.

WITH PCA

In [13]:
model=XGBClassifier(n_estimators= 200, max_depth= 3, learning_rate= 0.1)
model.fit(x1_train,y1_train)
gr_pred=model.predict(x1_test)
print(f"Accuracy: {accuracy_score(y1_test,gr_pred)}")    
print(f"Precision: {precision_score(y1_test,gr_pred)}")
print(f"Recall: {recall_score(y1_test,gr_pred)}")
print(f"F1 Score: {f1_score(y1_test,gr_pred)}")
print(f"ROC AUC Score: {roc_auc_score(y1_test,gr_pred)}")

Accuracy: 0.9405286343612335
Precision: 0.9207317073170732
Recall: 0.9151515151515152
F1 Score: 0.9179331306990881
ROC AUC Score: 0.9350844080947887

WITHOUT PCA

In [14]:
model=XGBClassifier(n_estimators= 200, max_depth= 3, learning_rate= 0.1)
model.fit(x2_train,y2_train)
gr_pred=model.predict(x2_test)
print(f"Accuracy: {accuracy_score(y2_test,gr_pred)}")    
print(f"Precision: {precision_score(y2_test,gr_pred)}")
print(f"Recall: {recall_score(y2_test,gr_pred)}")
print(f"F1 Score: {f1_score(y2_test,gr_pred)}")
print(f"ROC AUC Score: {roc_auc_score(y2_test,gr_pred)}")

Accuracy: 0.9405286343612335
Precision: 0.9207317073170732
Recall: 0.9151515151515152
F1 Score: 0.9179331306990881
ROC AUC Score: 0.9350844080947887